<#
.SYNOPSIS
    Automates the installation and configuration of Windows 11 Glass Desktop effects.

.DESCRIPTION
    This script installs and configures three tools to create a beautiful glass/translucent Windows 11 desktop:
    - MicaForEveryone: Applies Acrylic effects to application windows
    - TranslucentTB: Makes the taskbar translucent with Acrylic effect
    - ExplorerBlurMica: Adds Acrylic blur to File Explorer

.NOTES
    Requires Administrator privileges
    Requires Windows 10 (build 18362+) or Windows 11

.EXAMPLE
    Install-GlassDesktop

.EXAMPLE
    Uninstall-GlassDesktop
#>

#Requires -RunAsAdministrator

# Global variables
$Script:ExplorerBlurMicaPath = "C:\Program Files\ExplorerBlurMica"
$Script:ExplorerBlurMicaUrl = "https://github.com/Maplespe/ExplorerBlurMica/releases/download/2.0.1/Release_x64.zip"

function Test-Prerequisites {
    <#
    .SYNOPSIS
        Checks system prerequisites for glass desktop installation.
    #>
    Write-Host "`n=== Checking Prerequisites ===" -ForegroundColor Cyan

    # Check Windows version
    $os = Get-CimInstance Win32_OperatingSystem
    $build = [int]$os.BuildNumber

    Write-Host "Windows Version: $($os.Caption) (Build $build)" -ForegroundColor Gray

    if ($build -lt 18362) {
        Write-Host "ERROR: Windows 10 build 18362 or higher is required!" -ForegroundColor Red
        return $false
    }

    if ($build -ge 22000) {
        Write-Host "Windows 11 detected - Full Mica/Acrylic support available" -ForegroundColor Green
    } else {
        Write-Host "Windows 10 detected - Limited effect support" -ForegroundColor Yellow
    }

    return $true
}

function Install-WinGetIfMissing {
    <#
    .SYNOPSIS
        Ensures WinGet is installed on the system.
    #>
    Write-Host "`n=== Checking for WinGet ===" -ForegroundColor Cyan

    try {
        $winget = Get-Command winget -ErrorAction Stop
        Write-Host "WinGet found: $($winget.Source)" -ForegroundColor Green
        return $true
    } catch {
        Write-Host "WinGet not found. Installing..." -ForegroundColor Yellow

        try {
            # Install App Installer from Microsoft Store (includes WinGet)
            Write-Host "Installing Microsoft App Installer (this may take a moment)..." -ForegroundColor Gray
            $appInstallerUrl = "https://aka.ms/getwinget"
            Start-Process "ms-windows-store://pdp/?productid=9nblggh4nns1"
            Write-Host "Please install 'App Installer' from the Microsoft Store window that just opened." -ForegroundColor Yellow
            Write-Host "Press Enter once installation is complete..." -ForegroundColor Yellow
            Read-Host

            # Verify installation
            $winget = Get-Command winget -ErrorAction Stop
            Write-Host "WinGet successfully installed!" -ForegroundColor Green
            return $true
        } catch {
            Write-Host "ERROR: Failed to install WinGet. Please install manually from Microsoft Store." -ForegroundColor Red
            return $false
        }
    }
}

function Install-MicaForEveryone {
    <#
    .SYNOPSIS
        Installs and configures MicaForEveryone with Acrylic effects.
    #>
    Write-Host "`n=== Installing MicaForEveryone ===" -ForegroundColor Cyan

    try {
        # Install via WinGet
        Write-Host "Installing MicaForEveryone via WinGet..." -ForegroundColor Gray
        winget install --id=MicaForEveryone.MicaForEveryone -e --silent --accept-package-agreements --accept-source-agreements

        if ($LASTEXITCODE -eq 0) {
            Write-Host "MicaForEveryone installed successfully!" -ForegroundColor Green
        } else {
            throw "WinGet installation failed with exit code $LASTEXITCODE"
        }

        # Wait a moment for installation to complete
        Start-Sleep -Seconds 3

        # Create Acrylic configuration
        Write-Host "Configuring Acrylic effects..." -ForegroundColor Gray
        $configPath = "$env:LOCALAPPDATA\Mica For Everyone"

        if (-not (Test-Path $configPath)) {
            New-Item -ItemType Directory -Path $configPath -Force | Out-Null
        }

        $configFile = Join-Path $configPath "config.xcl"
        # Build config content line by line to avoid parser issues
        $configLines = @(
            '# MicaForEveryone Configuration - Acrylic Effects'
            '# Auto-generated by Install-GlassDesktop.ps1'
            ''
            'Global: "" {'
            '    TitleBarColor = Dark'
            '    BackdropPreference = Acrylic'
            '}'
            ''
            '# File Explorer gets Acrylic effect'
            'Class: "CabinetWClass" {'
            '    BackdropPreference = Acrylic'
            '    TitleBarColor = System'
            '}'
            ''
            '# Notepad'
            'Process: "notepad" {'
            '    BackdropPreference = Acrylic'
            '    TitleBarColor = System'
            '}'
        )

        $configLines | Out-File -FilePath $configFile -Encoding UTF8 -Force
        Write-Host "Configuration file created: $configFile" -ForegroundColor Green

        return $true
    } catch {
        Write-Host "ERROR: Failed to install MicaForEveryone: $_" -ForegroundColor Red
        return $false
    }
}

function Install-TranslucentTB {
    <#
    .SYNOPSIS
        Installs TranslucentTB for Acrylic taskbar effects.
    #>
    Write-Host "`n=== Installing TranslucentTB ===" -ForegroundColor Cyan

    try {
        # Install via WinGet
        Write-Host "Installing TranslucentTB via WinGet..." -ForegroundColor Gray
        winget install --id=CharlesMilette.TranslucentTB -e --silent --accept-package-agreements --accept-source-agreements

        if ($LASTEXITCODE -eq 0) {
            Write-Host "TranslucentTB installed successfully!" -ForegroundColor Green
        } else {
            throw "WinGet installation failed with exit code $LASTEXITCODE"
        }

        # Wait for installation to complete
        Start-Sleep -Seconds 3

        Write-Host "TranslucentTB will use Acrylic effect by default." -ForegroundColor Gray
        Write-Host "You can customize settings by right-clicking its system tray icon." -ForegroundColor Gray

        return $true
    } catch {
        Write-Host "ERROR: Failed to install TranslucentTB: $_" -ForegroundColor Red
        return $false
    }
}

function Install-ExplorerBlurMica {
    <#
    .SYNOPSIS
        Downloads, installs, and configures ExplorerBlurMica with Acrylic effects.
    #>
    Write-Host "`n=== Installing ExplorerBlurMica ===" -ForegroundColor Cyan

    try {
        # Download the release
        Write-Host "Downloading ExplorerBlurMica from GitHub..." -ForegroundColor Gray
        $zipPath = "$env:TEMP\ExplorerBlurMica.zip"

        Invoke-WebRequest -Uri $Script:ExplorerBlurMicaUrl -OutFile $zipPath -UseBasicParsing
        Write-Host "Downloaded to: $zipPath" -ForegroundColor Gray

        # Create installation directory
        if (-not (Test-Path $Script:ExplorerBlurMicaPath)) {
            New-Item -ItemType Directory -Path $Script:ExplorerBlurMicaPath -Force | Out-Null
        }

        # Extract files
        Write-Host "Extracting files to: $Script:ExplorerBlurMicaPath" -ForegroundColor Gray
        Expand-Archive -Path $zipPath -DestinationPath $Script:ExplorerBlurMicaPath -Force

        # Create config.ini with Acrylic effect
        Write-Host "Creating Acrylic configuration..." -ForegroundColor Gray
        $configContent = @'
[config]
effect=1
clearAddress=true
clearBarBg=false
clearWinUIBg=true
showLine=true

[light]
r=255
g=255
b=255
a=128

[dark]
r=32
g=32
b=32
a=192
'@

        $configPath = Join-Path $Script:ExplorerBlurMicaPath "config.ini"
        $configContent | Out-File -FilePath $configPath -Encoding UTF8 -Force
        Write-Host "Configuration file created: $configPath" -ForegroundColor Green

        # Register DLL
        Write-Host "Registering ExplorerBlurMica DLL..." -ForegroundColor Gray
        $dllPath = Join-Path $Script:ExplorerBlurMicaPath "ExplorerBlurMica.dll"

        if (-not (Test-Path $dllPath)) {
            throw "DLL not found at: $dllPath"
        }

        $process = Start-Process -FilePath "regsvr32.exe" -ArgumentList "/s `"$dllPath`"" -Wait -PassThru

        if ($process.ExitCode -eq 0) {
            Write-Host "DLL registered successfully!" -ForegroundColor Green
        } else {
            throw "Failed to register DLL (exit code: $($process.ExitCode))"
        }

        # Restart Explorer
        Write-Host "Restarting Windows Explorer to apply effects..." -ForegroundColor Yellow
        Stop-Process -Name explorer -Force
        Start-Sleep -Seconds 2

        Write-Host "ExplorerBlurMica installed and configured!" -ForegroundColor Green
        return $true

    } catch {
        Write-Host "ERROR: Failed to install ExplorerBlurMica: $_" -ForegroundColor Red
        return $false
    } finally {
        # Cleanup
        if (Test-Path $zipPath) {
            Remove-Item $zipPath -Force -ErrorAction SilentlyContinue
        }
    }
}

function Install-GlassDesktop {
    <#
    .SYNOPSIS
        Main installation function that orchestrates the entire glass desktop setup.
    #>
    Write-Host @"
╔═══════════════════════════════════════════════════════════╗
║                                                           ║
║        Windows 11 Glass Desktop Installation              ║
║                                                           ║
║   This will install and configure:                        ║
║   • MicaForEveryone (Acrylic window effects)             ║
║   • TranslucentTB (Acrylic taskbar)                      ║
║   • ExplorerBlurMica (Acrylic File Explorer)             ║
║                                                           ║
╚═══════════════════════════════════════════════════════════╝
"@ -ForegroundColor Cyan

    # Track installation results
    $results = @{
        Prerequisites = $false
        WinGet = $false
        MicaForEveryone = $false
        TranslucentTB = $false
        ExplorerBlurMica = $false
    }

    # Check prerequisites
    $results.Prerequisites = Test-Prerequisites
    if (-not $results.Prerequisites) {
        Write-Host "`nInstallation aborted due to failed prerequisites." -ForegroundColor Red
        return
    }

    # Install WinGet if needed
    $results.WinGet = Install-WinGetIfMissing
    if (-not $results.WinGet) {
        Write-Host "`nInstallation aborted: WinGet is required." -ForegroundColor Red
        return
    }

    # Install each component
    $results.MicaForEveryone = Install-MicaForEveryone
    $results.TranslucentTB = Install-TranslucentTB
    $results.ExplorerBlurMica = Install-ExplorerBlurMica

    # Summary
    Write-Host "`n╔═══════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
    Write-Host "║              Installation Summary                         ║" -ForegroundColor Cyan
    Write-Host "╚═══════════════════════════════════════════════════════════╝" -ForegroundColor Cyan

    Write-Host "`nComponent Status:" -ForegroundColor White
    Write-Host "  • MicaForEveryone:    $(if($results.MicaForEveryone){'✓ Installed'}else{'✗ Failed'})" -ForegroundColor $(if($results.MicaForEveryone){'Green'}else{'Red'})
    Write-Host "  • TranslucentTB:      $(if($results.TranslucentTB){'✓ Installed'}else{'✗ Failed'})" -ForegroundColor $(if($results.TranslucentTB){'Green'}else{'Red'})
    Write-Host "  • ExplorerBlurMica:   $(if($results.ExplorerBlurMica){'✓ Installed'}else{'✗ Failed'})" -ForegroundColor $(if($results.ExplorerBlurMica){'Green'}else{'Red'})

    $successCount = ($results.Values | Where-Object { $_ -eq $true }).Count - 2  # Exclude Prerequisites and WinGet

    if ($successCount -eq 3) {
        Write-Host "`n🎉 All components installed successfully!" -ForegroundColor Green
        Write-Host "`nNext Steps:" -ForegroundColor Cyan
        Write-Host "  1. Log out and log back in (or restart) for full effects" -ForegroundColor Gray
        Write-Host "  2. Launch MicaForEveryone and TranslucentTB from Start Menu" -ForegroundColor Gray
        Write-Host "  3. Right-click TranslucentTB tray icon to customize taskbar" -ForegroundColor Gray
        Write-Host "  4. Open File Explorer to see Acrylic blur effects" -ForegroundColor Gray
        Write-Host "`nTo uninstall, run: Uninstall-GlassDesktop" -ForegroundColor Yellow
    } else {
        Write-Host "`n⚠ Installation completed with some failures." -ForegroundColor Yellow
        Write-Host "Check the error messages above for details." -ForegroundColor Gray
    }
}

function Uninstall-GlassDesktop {
    <#
    .SYNOPSIS
        Removes all glass desktop components and restores default Windows appearance.
    #>
    Write-Host "`n╔═══════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
    Write-Host "║        Windows 11 Glass Desktop Uninstallation            ║" -ForegroundColor Cyan
    Write-Host "╚═══════════════════════════════════════════════════════════╝`n" -ForegroundColor Cyan

    $confirmation = Read-Host "Are you sure you want to uninstall all glass desktop components? (yes/no)"

    if ($confirmation -ne "yes") {
        Write-Host "Uninstallation cancelled." -ForegroundColor Yellow
        return
    }

    # Track uninstall results
    $results = @{
        MicaForEveryone = $false
        TranslucentTB = $false
        ExplorerBlurMica = $false
    }

    # Uninstall MicaForEveryone
    Write-Host "`nUninstalling MicaForEveryone..." -ForegroundColor Cyan
    try {
        winget uninstall --id=MicaForEveryone.MicaForEveryone -e --silent
        $results.MicaForEveryone = $true
        Write-Host "MicaForEveryone uninstalled." -ForegroundColor Green
    } catch {
        Write-Host "Failed to uninstall MicaForEveryone: $_" -ForegroundColor Red
    }

    # Uninstall TranslucentTB
    Write-Host "`nUninstalling TranslucentTB..." -ForegroundColor Cyan
    try {
        winget uninstall --id=CharlesMilette.TranslucentTB -e --silent
        $results.TranslucentTB = $true
        Write-Host "TranslucentTB uninstalled." -ForegroundColor Green
    } catch {
        Write-Host "Failed to uninstall TranslucentTB: $_" -ForegroundColor Red
    }

    # Uninstall ExplorerBlurMica
    Write-Host "`nUninstalling ExplorerBlurMica..." -ForegroundColor Cyan
    try {
        $dllPath = Join-Path $Script:ExplorerBlurMicaPath "ExplorerBlurMica.dll"

        if (Test-Path $dllPath) {
            # Unregister DLL
            Write-Host "Unregistering DLL..." -ForegroundColor Gray
            $process = Start-Process -FilePath "regsvr32.exe" -ArgumentList "/u /s `"$dllPath`"" -Wait -PassThru

            if ($process.ExitCode -eq 0) {
                Write-Host "DLL unregistered successfully." -ForegroundColor Green
            }
        }

        # Remove directory
        if (Test-Path $Script:ExplorerBlurMicaPath) {
            Write-Host "Removing installation directory..." -ForegroundColor Gray
            Remove-Item -Path $Script:ExplorerBlurMicaPath -Recurse -Force
        }

        $results.ExplorerBlurMica = $true
        Write-Host "ExplorerBlurMica uninstalled." -ForegroundColor Green

        # Restart Explorer
        Write-Host "Restarting Windows Explorer..." -ForegroundColor Yellow
        Stop-Process -Name explorer -Force
        Start-Sleep -Seconds 2

    } catch {
        Write-Host "Failed to uninstall ExplorerBlurMica: $_" -ForegroundColor Red
    }

    # Summary
    Write-Host "`n═══════════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "Uninstallation Summary:" -ForegroundColor White
    Write-Host "  • MicaForEveryone:    $(if($results.MicaForEveryone){'✓ Removed'}else{'✗ Failed'})" -ForegroundColor $(if($results.MicaForEveryone){'Green'}else{'Red'})
    Write-Host "  • TranslucentTB:      $(if($results.TranslucentTB){'✓ Removed'}else{'✗ Failed'})" -ForegroundColor $(if($results.TranslucentTB){'Green'}else{'Red'})
    Write-Host "  • ExplorerBlurMica:   $(if($results.ExplorerBlurMica){'✓ Removed'}else{'✗ Failed'})" -ForegroundColor $(if($results.ExplorerBlurMica){'Green'}else{'Red'})

    $successCount = ($results.Values | Where-Object { $_ -eq $true }).Count

    if ($successCount -eq 3) {
        Write-Host "`n✓ All components removed successfully!" -ForegroundColor Green
        Write-Host "Your Windows desktop has been restored to default appearance." -ForegroundColor Gray
    } else {
        Write-Host "`n⚠ Uninstallation completed with some failures." -ForegroundColor Yellow
    }
}

# Export functions
Export-ModuleMember -Function Install-GlassDesktop, Uninstall-GlassDesktop

# Display usage information if script is run directly
if ($MyInvocation.InvocationName -ne '.') {
    Write-Host @"
╔═══════════════════════════════════════════════════════════╗
║                                                           ║
║        Windows 11 Glass Desktop Automation Script         ║
║                                                           ║
╚═══════════════════════════════════════════════════════════╝

Usage:
  Install:   Install-GlassDesktop
  Uninstall: Uninstall-GlassDesktop

What this script does:
  • Installs MicaForEveryone for Acrylic window effects
  • Installs TranslucentTB for Acrylic taskbar
  • Installs ExplorerBlurMica for Acrylic File Explorer
  • Configures all tools with Acrylic visual effects
  • Provides easy uninstall function

Requirements:
  • Windows 10 (build 18362+) or Windows 11
  • Administrator privileges
  • Internet connection

Examples:
  .\Install-GlassDesktop.ps1; Install-GlassDesktop
  .\Install-GlassDesktop.ps1; Uninstall-GlassDesktop

"@ -ForegroundColor Cyan
}
